[build]
  command = "hugo --gc --minify"
  publish = "public"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.154.3"

[context.production.environment]
  HUGO_ENV = "production"
  HUGO_VERSION = "0.154.3"

[dev]
  framework = "hugo"

[[redirects]]
  from = "https://muitapeixe-nunogodinho.com.netlify.com/*"
  to = "https://muitapeixe.nunogodinho.com/:splat"
  status = 301
  force = true

[[headers]]
  for = "/*"

  [headers.values]
    X-XSS-Protection = "1; mode=block"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Strict-Transport-Security = "max-age=15768000; includeSubDomains"
    Referrer-Policy = "no-referrer"
    Content-Security-Policy = "default-src 'self'; form-action 'none'; frame-ancestors 'none'; script-src 'self' 'unsafe-eval';"

#[[plugins]]
  #package = "@netlify/plugin-sitemap"

#[[plugins]]
  #package = "netlify-plugin-submit-sitemap"
  #pinned_version = "0.4.0"

#[[plugins]]
  #package = "netlify-plugin-checklinks"

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"

[plugins.inputs]
  debug = false

[[plugins]]
  package = "@netlify/plugin-lighthouse"
  pinned_version = "5.0.0"

[plugins.inputs]
    output_path = "reports/lighthouse.html"
